version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.dockerfile
      context: .
    restart: always
    volumes:
      - "./html/:/var/www/html/"
    ports:
      - "8080:80"
  mysql-server:
    image: mysql:8.0.19
    restart: always
    command: --init-file /data/application/init.sql
    volumes:
        - mysql-data:/var/lib/mysql
        - ./init.sql:/data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: Be@rD0wN!
      

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: Be@rD0wN!
    ports:
      - "5000:80"
volumes:
  mysql-data: